[package]
name = "yew-todo"
version = "0.1.0"
authors = ["putchom <putchom8@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.40"
http = "0.2.4"
serde = "1.0.126"
wasm-bindgen = "0.2.74"
yew = "0.18.0"
