[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
dependencies = ["compile_scss"]
watch = { ignore_pattern = "static/*" }

[tasks.serve]
command = "simple-http-server"
args = ["-i", "./static/", "-p", "8080", "--nocache", "--try-file", "./static/index.html"]

[tasks.compile_scss]
script = [
  "npm run build:sass"
]
watch = true